### ISSUE TITLE
Installer does not copy hud colour preset files

### ISSUE THREAD

**Issue by MoerasGrizzly** [Shivansps/Knossos.NET#3]
When extracting a new installation from a GOG installer, Knossos.net doesn't copy the hud_x.hcf files that are found in data/players in a normal FS2 install.

This isn't a big deal, but it does mean that FSO will default to the green hud rather then to the somewhat more neatly designed colours found in the hud presets.

(it should probably also extract the retail .exe)

**Comment by Shivansps** [comment]
im going to be completely honest here, this is the first time i learn about the hud presets profiles and ive been playing this since 1999.
This should be fixed for the next 0.1.2 release.
